remote_theme: jekyll/minima
title: OmniTangent
description: Reflecting on AI, Tech, Game development, e-commerce and more
default_lang: en
languages:
  - en
  - zh
google_analytics: G-S4NDZ0GWCT
utterances:
  repo: "ztangents/ztangents"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-light"
